// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobufs/poker.proto

package poker

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Round_Status int32

const (
	Round_NOT_STARTED Round_Status = 0
	Round_PRE_FLOP    Round_Status = 1
	Round_FLOP        Round_Status = 2
	Round_RIVER       Round_Status = 3
	Round_TURN        Round_Status = 4
	Round_SHOW        Round_Status = 5
	Round_OVER        Round_Status = 6
)

var Round_Status_name = map[int32]string{
	0: "NOT_STARTED",
	1: "PRE_FLOP",
	2: "FLOP",
	3: "RIVER",
	4: "TURN",
	5: "SHOW",
	6: "OVER",
}

var Round_Status_value = map[string]int32{
	"NOT_STARTED": 0,
	"PRE_FLOP":    1,
	"FLOP":        2,
	"RIVER":       3,
	"TURN":        4,
	"SHOW":        5,
	"OVER":        6,
}

func (x Round_Status) String() string {
	return proto.EnumName(Round_Status_name, int32(x))
}

func (Round_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_818c499f6358623d, []int{4, 0}
}

type Bet_Status int32

const (
	Bet_NOT_STARTED Bet_Status = 0
	Bet_PRE_FLOP    Bet_Status = 1
	Bet_FLOP        Bet_Status = 2
	Bet_RIVER       Bet_Status = 3
	Bet_TURN        Bet_Status = 4
	Bet_SHOW        Bet_Status = 5
	Bet_OVER        Bet_Status = 6
)

var Bet_Status_name = map[int32]string{
	0: "NOT_STARTED",
	1: "PRE_FLOP",
	2: "FLOP",
	3: "RIVER",
	4: "TURN",
	5: "SHOW",
	6: "OVER",
}

var Bet_Status_value = map[string]int32{
	"NOT_STARTED": 0,
	"PRE_FLOP":    1,
	"FLOP":        2,
	"RIVER":       3,
	"TURN":        4,
	"SHOW":        5,
	"OVER":        6,
}

func (x Bet_Status) String() string {
	return proto.EnumName(Bet_Status_name, int32(x))
}

func (Bet_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_818c499f6358623d, []int{6, 0}
}

type Bet_BetType int32

const (
	Bet_NONE  Bet_BetType = 0
	Bet_FOLD  Bet_BetType = 1
	Bet_CALL  Bet_BetType = 2
	Bet_RAISE Bet_BetType = 3
)

var Bet_BetType_name = map[int32]string{
	0: "NONE",
	1: "FOLD",
	2: "CALL",
	3: "RAISE",
}

var Bet_BetType_value = map[string]int32{
	"NONE":  0,
	"FOLD":  1,
	"CALL":  2,
	"RAISE": 3,
}

func (x Bet_BetType) String() string {
	return proto.EnumName(Bet_BetType_name, int32(x))
}

func (Bet_BetType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_818c499f6358623d, []int{6, 1}
}

type Player struct {
	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Chips int64  `protobuf:"varint,3,opt,name=chips,proto3" json:"chips,omitempty"`
	// What seat at the table they are at 1-8 only
	Slot int64 `protobuf:"varint,4,opt,name=slot,proto3" json:"slot,omitempty"`
	// Whether they are in a hand
	InHand               bool     `protobuf:"varint,5,opt,name=in_hand,json=inHand,proto3" json:"in_hand,omitempty"`
	Cards                string   `protobuf:"bytes,6,opt,name=cards,proto3" json:"cards,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_818c499f6358623d, []int{0}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetChips() int64 {
	if m != nil {
		return m.Chips
	}
	return 0
}

func (m *Player) GetSlot() int64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *Player) GetInHand() bool {
	if m != nil {
		return m.InHand
	}
	return false
}

func (m *Player) GetCards() string {
	if m != nil {
		return m.Cards
	}
	return ""
}

type Players struct {
	Players              []*Player `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Players) Reset()         { *m = Players{} }
func (m *Players) String() string { return proto.CompactTextString(m) }
func (*Players) ProtoMessage()    {}
func (*Players) Descriptor() ([]byte, []int) {
	return fileDescriptor_818c499f6358623d, []int{1}
}

func (m *Players) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Players.Unmarshal(m, b)
}
func (m *Players) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Players.Marshal(b, m, deterministic)
}
func (m *Players) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Players.Merge(m, src)
}
func (m *Players) XXX_Size() int {
	return xxx_messageInfo_Players.Size(m)
}
func (m *Players) XXX_DiscardUnknown() {
	xxx_messageInfo_Players.DiscardUnknown(m)
}

var xxx_messageInfo_Players proto.InternalMessageInfo

func (m *Players) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

type Game struct {
	Players *Players `protobuf:"bytes,1,opt,name=players,proto3" json:"players,omitempty"`
	Name    string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// button positions
	Id                   int64    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Dealer               int64    `protobuf:"varint,4,opt,name=dealer,proto3" json:"dealer,omitempty"`
	Min                  int64    `protobuf:"varint,5,opt,name=min,proto3" json:"min,omitempty"`
	Rounds               *Rounds  `protobuf:"bytes,6,opt,name=rounds,proto3" json:"rounds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game) Reset()         { *m = Game{} }
func (m *Game) String() string { return proto.CompactTextString(m) }
func (*Game) ProtoMessage()    {}
func (*Game) Descriptor() ([]byte, []int) {
	return fileDescriptor_818c499f6358623d, []int{2}
}

func (m *Game) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game.Unmarshal(m, b)
}
func (m *Game) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game.Marshal(b, m, deterministic)
}
func (m *Game) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game.Merge(m, src)
}
func (m *Game) XXX_Size() int {
	return xxx_messageInfo_Game.Size(m)
}
func (m *Game) XXX_DiscardUnknown() {
	xxx_messageInfo_Game.DiscardUnknown(m)
}

var xxx_messageInfo_Game proto.InternalMessageInfo

func (m *Game) GetPlayers() *Players {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *Game) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Game) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Game) GetDealer() int64 {
	if m != nil {
		return m.Dealer
	}
	return 0
}

func (m *Game) GetMin() int64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *Game) GetRounds() *Rounds {
	if m != nil {
		return m.Rounds
	}
	return nil
}

type Games struct {
	Games                []*Game  `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Games) Reset()         { *m = Games{} }
func (m *Games) String() string { return proto.CompactTextString(m) }
func (*Games) ProtoMessage()    {}
func (*Games) Descriptor() ([]byte, []int) {
	return fileDescriptor_818c499f6358623d, []int{3}
}

func (m *Games) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Games.Unmarshal(m, b)
}
func (m *Games) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Games.Marshal(b, m, deterministic)
}
func (m *Games) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Games.Merge(m, src)
}
func (m *Games) XXX_Size() int {
	return xxx_messageInfo_Games.Size(m)
}
func (m *Games) XXX_DiscardUnknown() {
	xxx_messageInfo_Games.DiscardUnknown(m)
}

var xxx_messageInfo_Games proto.InternalMessageInfo

func (m *Games) GetGames() []*Game {
	if m != nil {
		return m.Games
	}
	return nil
}

// any info here is only relevant within a particular hand
type Round struct {
	Id                   int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               Round_Status `protobuf:"varint,2,opt,name=status,proto3,enum=poker.Round_Status" json:"status,omitempty"`
	Players              *Players     `protobuf:"bytes,3,opt,name=players,proto3" json:"players,omitempty"`
	Deck                 string       `protobuf:"bytes,4,opt,name=deck,proto3" json:"deck,omitempty"`
	Flop                 string       `protobuf:"bytes,5,opt,name=flop,proto3" json:"flop,omitempty"`
	Turn                 string       `protobuf:"bytes,6,opt,name=turn,proto3" json:"turn,omitempty"`
	River                string       `protobuf:"bytes,7,opt,name=river,proto3" json:"river,omitempty"`
	Bets                 *Bets        `protobuf:"bytes,8,opt,name=bets,proto3" json:"bets,omitempty"`
	Game                 int64        `protobuf:"varint,9,opt,name=game,proto3" json:"game,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Round) Reset()         { *m = Round{} }
func (m *Round) String() string { return proto.CompactTextString(m) }
func (*Round) ProtoMessage()    {}
func (*Round) Descriptor() ([]byte, []int) {
	return fileDescriptor_818c499f6358623d, []int{4}
}

func (m *Round) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Round.Unmarshal(m, b)
}
func (m *Round) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Round.Marshal(b, m, deterministic)
}
func (m *Round) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Round.Merge(m, src)
}
func (m *Round) XXX_Size() int {
	return xxx_messageInfo_Round.Size(m)
}
func (m *Round) XXX_DiscardUnknown() {
	xxx_messageInfo_Round.DiscardUnknown(m)
}

var xxx_messageInfo_Round proto.InternalMessageInfo

func (m *Round) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Round) GetStatus() Round_Status {
	if m != nil {
		return m.Status
	}
	return Round_NOT_STARTED
}

func (m *Round) GetPlayers() *Players {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *Round) GetDeck() string {
	if m != nil {
		return m.Deck
	}
	return ""
}

func (m *Round) GetFlop() string {
	if m != nil {
		return m.Flop
	}
	return ""
}

func (m *Round) GetTurn() string {
	if m != nil {
		return m.Turn
	}
	return ""
}

func (m *Round) GetRiver() string {
	if m != nil {
		return m.River
	}
	return ""
}

func (m *Round) GetBets() *Bets {
	if m != nil {
		return m.Bets
	}
	return nil
}

func (m *Round) GetGame() int64 {
	if m != nil {
		return m.Game
	}
	return 0
}

type Rounds struct {
	Rounds               []*Round `protobuf:"bytes,1,rep,name=rounds,proto3" json:"rounds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rounds) Reset()         { *m = Rounds{} }
func (m *Rounds) String() string { return proto.CompactTextString(m) }
func (*Rounds) ProtoMessage()    {}
func (*Rounds) Descriptor() ([]byte, []int) {
	return fileDescriptor_818c499f6358623d, []int{5}
}

func (m *Rounds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rounds.Unmarshal(m, b)
}
func (m *Rounds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rounds.Marshal(b, m, deterministic)
}
func (m *Rounds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rounds.Merge(m, src)
}
func (m *Rounds) XXX_Size() int {
	return xxx_messageInfo_Rounds.Size(m)
}
func (m *Rounds) XXX_DiscardUnknown() {
	xxx_messageInfo_Rounds.DiscardUnknown(m)
}

var xxx_messageInfo_Rounds proto.InternalMessageInfo

func (m *Rounds) GetRounds() []*Round {
	if m != nil {
		return m.Rounds
	}
	return nil
}

type Bet struct {
	Id                   int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               Bet_Status  `protobuf:"varint,2,opt,name=status,proto3,enum=poker.Bet_Status" json:"status,omitempty"`
	Round                int64       `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	Game                 int64       `protobuf:"varint,4,opt,name=game,proto3" json:"game,omitempty"`
	Player               int64       `protobuf:"varint,5,opt,name=player,proto3" json:"player,omitempty"`
	Chips                int64       `protobuf:"varint,6,opt,name=chips,proto3" json:"chips,omitempty"`
	Type                 Bet_BetType `protobuf:"varint,7,opt,name=type,proto3,enum=poker.Bet_BetType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Bet) Reset()         { *m = Bet{} }
func (m *Bet) String() string { return proto.CompactTextString(m) }
func (*Bet) ProtoMessage()    {}
func (*Bet) Descriptor() ([]byte, []int) {
	return fileDescriptor_818c499f6358623d, []int{6}
}

func (m *Bet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bet.Unmarshal(m, b)
}
func (m *Bet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bet.Marshal(b, m, deterministic)
}
func (m *Bet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bet.Merge(m, src)
}
func (m *Bet) XXX_Size() int {
	return xxx_messageInfo_Bet.Size(m)
}
func (m *Bet) XXX_DiscardUnknown() {
	xxx_messageInfo_Bet.DiscardUnknown(m)
}

var xxx_messageInfo_Bet proto.InternalMessageInfo

func (m *Bet) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Bet) GetStatus() Bet_Status {
	if m != nil {
		return m.Status
	}
	return Bet_NOT_STARTED
}

func (m *Bet) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *Bet) GetGame() int64 {
	if m != nil {
		return m.Game
	}
	return 0
}

func (m *Bet) GetPlayer() int64 {
	if m != nil {
		return m.Player
	}
	return 0
}

func (m *Bet) GetChips() int64 {
	if m != nil {
		return m.Chips
	}
	return 0
}

func (m *Bet) GetType() Bet_BetType {
	if m != nil {
		return m.Type
	}
	return Bet_NONE
}

type Bets struct {
	Bets                 []*Bet   `protobuf:"bytes,1,rep,name=bets,proto3" json:"bets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bets) Reset()         { *m = Bets{} }
func (m *Bets) String() string { return proto.CompactTextString(m) }
func (*Bets) ProtoMessage()    {}
func (*Bets) Descriptor() ([]byte, []int) {
	return fileDescriptor_818c499f6358623d, []int{7}
}

func (m *Bets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bets.Unmarshal(m, b)
}
func (m *Bets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bets.Marshal(b, m, deterministic)
}
func (m *Bets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bets.Merge(m, src)
}
func (m *Bets) XXX_Size() int {
	return xxx_messageInfo_Bets.Size(m)
}
func (m *Bets) XXX_DiscardUnknown() {
	xxx_messageInfo_Bets.DiscardUnknown(m)
}

var xxx_messageInfo_Bets proto.InternalMessageInfo

func (m *Bets) GetBets() []*Bet {
	if m != nil {
		return m.Bets
	}
	return nil
}

func init() {
	proto.RegisterEnum("poker.Round_Status", Round_Status_name, Round_Status_value)
	proto.RegisterEnum("poker.Bet_Status", Bet_Status_name, Bet_Status_value)
	proto.RegisterEnum("poker.Bet_BetType", Bet_BetType_name, Bet_BetType_value)
	proto.RegisterType((*Player)(nil), "poker.Player")
	proto.RegisterType((*Players)(nil), "poker.Players")
	proto.RegisterType((*Game)(nil), "poker.Game")
	proto.RegisterType((*Games)(nil), "poker.Games")
	proto.RegisterType((*Round)(nil), "poker.Round")
	proto.RegisterType((*Rounds)(nil), "poker.Rounds")
	proto.RegisterType((*Bet)(nil), "poker.Bet")
	proto.RegisterType((*Bets)(nil), "poker.Bets")
}

func init() { proto.RegisterFile("protobufs/poker.proto", fileDescriptor_818c499f6358623d) }

var fileDescriptor_818c499f6358623d = []byte{
	// 823 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0x8e, 0xe3, 0x9f, 0x24, 0x27, 0x3f, 0xeb, 0x1d, 0x96, 0x62, 0x05, 0x09, 0x82, 0xc5, 0x2e,
	0x86, 0x0a, 0x07, 0x02, 0x08, 0x71, 0x85, 0x92, 0x4d, 0xb6, 0xad, 0x14, 0x25, 0xd1, 0x38, 0x14,
	0x89, 0x9b, 0xca, 0xad, 0xa7, 0xad, 0x55, 0xc7, 0xb6, 0xec, 0x49, 0x45, 0x1e, 0x80, 0x47, 0xe1,
	0x7d, 0xe0, 0x82, 0xf7, 0x41, 0xf3, 0x93, 0xc4, 0x49, 0x69, 0xc2, 0xcd, 0xde, 0x9d, 0xff, 0x39,
	0xdf, 0xf9, 0x8e, 0x8f, 0xe1, 0xc3, 0x34, 0x4b, 0x68, 0x72, 0xbd, 0xbc, 0xcd, 0xbb, 0x69, 0xf2,
	0x40, 0x32, 0x97, 0xeb, 0x48, 0xe7, 0x4a, 0xfb, 0xe3, 0xbb, 0x24, 0xb9, 0x8b, 0x48, 0x77, 0x1d,
	0xd4, 0x25, 0x8b, 0x94, 0xae, 0x44, 0x8c, 0xfd, 0x87, 0x02, 0xc6, 0x2c, 0xf2, 0x57, 0x24, 0x43,
	0x2d, 0x28, 0x87, 0x81, 0xa5, 0x74, 0x14, 0x47, 0xc5, 0xe5, 0x30, 0x40, 0x08, 0xb4, 0xd8, 0x5f,
	0x10, 0xab, 0xdc, 0x51, 0x9c, 0x1a, 0xe6, 0x32, 0x7a, 0x05, 0xfa, 0xcd, 0x7d, 0x98, 0xe6, 0x96,
	0xca, 0xc3, 0x84, 0xc2, 0x22, 0xf3, 0x28, 0xa1, 0x96, 0xc6, 0x8d, 0x5c, 0x46, 0x1f, 0x41, 0x25,
	0x8c, 0xaf, 0xee, 0xfd, 0x38, 0xb0, 0xf4, 0x8e, 0xe2, 0x54, 0xb1, 0x11, 0xc6, 0xe7, 0x7e, 0x1c,
	0xf0, 0x12, 0x7e, 0x16, 0xe4, 0x96, 0xc1, 0xeb, 0x0a, 0xc5, 0xee, 0x41, 0x45, 0xb4, 0x91, 0xa3,
	0x2f, 0xa0, 0x92, 0x0a, 0xd1, 0x52, 0x3a, 0xaa, 0x53, 0xef, 0x35, 0x5d, 0x81, 0x4a, 0x04, 0xe0,
	0xb5, 0xd7, 0xfe, 0x53, 0x01, 0xed, 0x8c, 0x75, 0xe5, 0x14, 0x33, 0x14, 0xa7, 0xde, 0x6b, 0xed,
	0x64, 0xe4, 0x9b, 0x94, 0xff, 0xc4, 0x24, 0x70, 0xab, 0x1b, 0xdc, 0x27, 0x60, 0x04, 0xc4, 0x8f,
	0x48, 0x26, 0xf1, 0x48, 0x0d, 0x99, 0xa0, 0x2e, 0xc2, 0x98, 0xa3, 0x51, 0x31, 0x13, 0xd1, 0x6b,
	0x30, 0xb2, 0x64, 0x19, 0x4b, 0x2c, 0xdb, 0x46, 0x31, 0x37, 0x62, 0xe9, 0xb4, 0xbf, 0x02, 0x9d,
	0xb5, 0x99, 0xa3, 0xcf, 0x40, 0xbf, 0x63, 0x82, 0xc4, 0x55, 0x97, 0xe1, 0xcc, 0x89, 0x85, 0xc7,
	0xfe, 0xbb, 0x0c, 0x3a, 0x4f, 0x7f, 0x42, 0xc7, 0x29, 0x18, 0x39, 0xf5, 0xe9, 0x32, 0xe7, 0xcd,
	0xb7, 0x7a, 0x1f, 0x14, 0x1f, 0x73, 0x3d, 0xee, 0xc2, 0x32, 0xa4, 0x38, 0x11, 0xf5, 0xe8, 0x44,
	0x02, 0x72, 0xf3, 0xc0, 0xb1, 0xd6, 0x30, 0x97, 0x99, 0xed, 0x36, 0x4a, 0x52, 0x0e, 0xb5, 0x86,
	0xb9, 0xcc, 0x6c, 0x74, 0x99, 0xc5, 0x92, 0x35, 0x2e, 0x33, 0x2a, 0xb3, 0xf0, 0x91, 0x64, 0x56,
	0x45, 0x50, 0xc9, 0x15, 0xf4, 0x29, 0x68, 0xd7, 0x84, 0xe6, 0x56, 0x95, 0x3f, 0xbc, 0x06, 0x39,
	0x20, 0x34, 0xc7, 0xdc, 0xc1, 0x4a, 0x31, 0xb0, 0x56, 0x4d, 0xac, 0x0b, 0x93, 0xed, 0xdf, 0xc0,
	0x10, 0x10, 0xd0, 0x0b, 0xa8, 0x4f, 0xa6, 0xf3, 0x2b, 0x6f, 0xde, 0xc7, 0xf3, 0xd1, 0xd0, 0x2c,
	0xa1, 0x06, 0x54, 0x67, 0x78, 0x74, 0xf5, 0x6e, 0x3c, 0x9d, 0x99, 0x0a, 0xaa, 0x82, 0xc6, 0xa5,
	0x32, 0xaa, 0x81, 0x8e, 0x2f, 0x2e, 0x47, 0xd8, 0x54, 0x99, 0x71, 0xfe, 0x0b, 0x9e, 0x98, 0x1a,
	0x93, 0xbc, 0xf3, 0xe9, 0xaf, 0xa6, 0xce, 0xa4, 0x29, 0xf3, 0x1a, 0xb6, 0x0b, 0x86, 0x60, 0x04,
	0x7d, 0xbe, 0x21, 0x4c, 0x30, 0xd0, 0x28, 0xce, 0x70, 0xc3, 0xd7, 0x5f, 0x65, 0x50, 0x07, 0x84,
	0x3e, 0x61, 0xe0, 0xcb, 0x3d, 0x06, 0x5e, 0x6e, 0xa1, 0xed, 0xcf, 0x9f, 0x4d, 0x86, 0x15, 0x5b,
	0x7f, 0x27, 0x5c, 0xd9, 0x00, 0xd7, 0xb6, 0xc0, 0xd9, 0xb6, 0x09, 0x2a, 0xe4, 0x62, 0x49, 0x6d,
	0xfb, 0xa5, 0x19, 0xc5, 0x2f, 0xed, 0x0d, 0x68, 0x74, 0x95, 0x12, 0x3e, 0xf0, 0x56, 0x0f, 0x15,
	0x1a, 0x18, 0x10, 0x3a, 0x5f, 0xa5, 0x04, 0x73, 0xff, 0x7b, 0x1d, 0x67, 0x0f, 0x2a, 0xf2, 0x31,
	0x66, 0x9c, 0x4c, 0x27, 0x23, 0xb3, 0xc4, 0xeb, 0x4c, 0xc7, 0x43, 0x51, 0xf1, 0x6d, 0x7f, 0x3c,
	0x96, 0x15, 0xfb, 0x17, 0xde, 0xc8, 0x54, 0xed, 0x37, 0xa0, 0xb1, 0x05, 0x40, 0x9f, 0xc8, 0xdd,
	0x10, 0xe3, 0x87, 0x6d, 0xff, 0x62, 0x35, 0x7a, 0xff, 0x18, 0xa0, 0xcf, 0x98, 0x0d, 0xb9, 0xd0,
	0x78, 0x9b, 0x11, 0x9f, 0x12, 0x79, 0x9d, 0x76, 0x8f, 0x40, 0x7b, 0x57, 0xb5, 0x4b, 0xe8, 0x5b,
	0x68, 0x16, 0xe3, 0x73, 0xb4, 0xb7, 0xf1, 0xed, 0x3d, 0xdd, 0x2e, 0xa1, 0x9f, 0xa0, 0x39, 0x24,
	0x11, 0x79, 0x3e, 0xe5, 0xc4, 0x15, 0xa7, 0xd3, 0x5d, 0x9f, 0x4e, 0x77, 0xc4, 0x4e, 0xa7, 0x5d,
	0x42, 0xa7, 0x50, 0x3b, 0x23, 0xf4, 0x7f, 0xb6, 0xe6, 0x00, 0x88, 0xd6, 0xf8, 0xb1, 0x2a, 0x7e,
	0xf5, 0xed, 0xa2, 0x62, 0x97, 0xd0, 0x6b, 0xa8, 0x9c, 0x11, 0x7a, 0x34, 0xec, 0x07, 0xa8, 0x8b,
	0xc6, 0xc5, 0x59, 0x69, 0x14, 0xbc, 0x87, 0x9a, 0xfe, 0x11, 0x4e, 0x64, 0x75, 0x09, 0x70, 0xb0,
	0x62, 0xca, 0x45, 0xb0, 0xfb, 0xd8, 0xd3, 0x41, 0x9d, 0x42, 0x53, 0x26, 0x0e, 0x56, 0x93, 0x63,
	0xcd, 0x75, 0xa1, 0xe5, 0xed, 0xbc, 0x72, 0xac, 0xfa, 0xf7, 0x60, 0x6e, 0x66, 0x99, 0xcb, 0x07,
	0x8e, 0x93, 0xd7, 0x85, 0xa6, 0xb7, 0xce, 0xf2, 0xd8, 0x0f, 0xe7, 0x18, 0x0b, 0x5d, 0x78, 0xd9,
	0x8f, 0xa2, 0xe4, 0x46, 0xf2, 0xc0, 0x72, 0xf2, 0x83, 0x40, 0xbe, 0x01, 0xe4, 0x11, 0x3a, 0x58,
	0x52, 0x9a, 0xc4, 0xb3, 0x24, 0x0f, 0x69, 0x98, 0xc4, 0x87, 0x33, 0xbe, 0x86, 0x17, 0x97, 0x7e,
	0x14, 0x06, 0x6c, 0x0b, 0xb3, 0xe3, 0x6c, 0x3b, 0x00, 0x13, 0xf2, 0x3b, 0x1d, 0x8a, 0xdf, 0xcb,
	0xa1, 0xc8, 0x9f, 0xe1, 0x15, 0x26, 0x8b, 0xe4, 0x51, 0x8e, 0xf4, 0x5d, 0x96, 0x2c, 0x78, 0xf5,
	0x3d, 0xcc, 0xcf, 0x52, 0x7f, 0x6d, 0x70, 0xcb, 0x77, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xc5,
	0xf1, 0xff, 0x7f, 0x2a, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PokerClient is the client API for Poker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PokerClient interface {
	CreatePlayer(ctx context.Context, in *Player, opts ...grpc.CallOption) (*Player, error)
	CreatePlayers(ctx context.Context, in *Players, opts ...grpc.CallOption) (*Players, error)
	DeletePlayers(ctx context.Context, in *Players, opts ...grpc.CallOption) (*empty.Empty, error)
	GetPlayer(ctx context.Context, in *Player, opts ...grpc.CallOption) (*Player, error)
	CreateGame(ctx context.Context, in *Game, opts ...grpc.CallOption) (*Game, error)
	GetGame(ctx context.Context, in *Game, opts ...grpc.CallOption) (*Game, error)
	DeleteGames(ctx context.Context, in *Games, opts ...grpc.CallOption) (*empty.Empty, error)
	GetGamePlayersByGameId(ctx context.Context, in *Game, opts ...grpc.CallOption) (*Players, error)
	GetGameByName(ctx context.Context, in *Game, opts ...grpc.CallOption) (*Game, error)
	SetGamePlayers(ctx context.Context, in *Game, opts ...grpc.CallOption) (*Players, error)
	GetPlayersByName(ctx context.Context, in *Players, opts ...grpc.CallOption) (*Players, error)
	SetPlayerSlot(ctx context.Context, in *Player, opts ...grpc.CallOption) (*Player, error)
	AllocateGameSlots(ctx context.Context, in *Game, opts ...grpc.CallOption) (*Game, error)
	SetButtonPositions(ctx context.Context, in *Game, opts ...grpc.CallOption) (*Game, error)
	ValidatePreGame(ctx context.Context, in *Game, opts ...grpc.CallOption) (*Game, error)
	NextDealer(ctx context.Context, in *Game, opts ...grpc.CallOption) (*Game, error)
	//    rpc CreateRoundFromGame(Game) returns (Round){}
	//    rpc GetRoundsFromGame(Game) returns (Round){}
	RemovePlayerFromGame(ctx context.Context, in *Player, opts ...grpc.CallOption) (*empty.Empty, error)
}

type pokerClient struct {
	cc *grpc.ClientConn
}

func NewPokerClient(cc *grpc.ClientConn) PokerClient {
	return &pokerClient{cc}
}

func (c *pokerClient) CreatePlayer(ctx context.Context, in *Player, opts ...grpc.CallOption) (*Player, error) {
	out := new(Player)
	err := c.cc.Invoke(ctx, "/poker.Poker/CreatePlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerClient) CreatePlayers(ctx context.Context, in *Players, opts ...grpc.CallOption) (*Players, error) {
	out := new(Players)
	err := c.cc.Invoke(ctx, "/poker.Poker/CreatePlayers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerClient) DeletePlayers(ctx context.Context, in *Players, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/poker.Poker/DeletePlayers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerClient) GetPlayer(ctx context.Context, in *Player, opts ...grpc.CallOption) (*Player, error) {
	out := new(Player)
	err := c.cc.Invoke(ctx, "/poker.Poker/GetPlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerClient) CreateGame(ctx context.Context, in *Game, opts ...grpc.CallOption) (*Game, error) {
	out := new(Game)
	err := c.cc.Invoke(ctx, "/poker.Poker/CreateGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerClient) GetGame(ctx context.Context, in *Game, opts ...grpc.CallOption) (*Game, error) {
	out := new(Game)
	err := c.cc.Invoke(ctx, "/poker.Poker/GetGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerClient) DeleteGames(ctx context.Context, in *Games, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/poker.Poker/DeleteGames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerClient) GetGamePlayersByGameId(ctx context.Context, in *Game, opts ...grpc.CallOption) (*Players, error) {
	out := new(Players)
	err := c.cc.Invoke(ctx, "/poker.Poker/GetGamePlayersByGameId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerClient) GetGameByName(ctx context.Context, in *Game, opts ...grpc.CallOption) (*Game, error) {
	out := new(Game)
	err := c.cc.Invoke(ctx, "/poker.Poker/GetGameByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerClient) SetGamePlayers(ctx context.Context, in *Game, opts ...grpc.CallOption) (*Players, error) {
	out := new(Players)
	err := c.cc.Invoke(ctx, "/poker.Poker/SetGamePlayers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerClient) GetPlayersByName(ctx context.Context, in *Players, opts ...grpc.CallOption) (*Players, error) {
	out := new(Players)
	err := c.cc.Invoke(ctx, "/poker.Poker/GetPlayersByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerClient) SetPlayerSlot(ctx context.Context, in *Player, opts ...grpc.CallOption) (*Player, error) {
	out := new(Player)
	err := c.cc.Invoke(ctx, "/poker.Poker/SetPlayerSlot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerClient) AllocateGameSlots(ctx context.Context, in *Game, opts ...grpc.CallOption) (*Game, error) {
	out := new(Game)
	err := c.cc.Invoke(ctx, "/poker.Poker/AllocateGameSlots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerClient) SetButtonPositions(ctx context.Context, in *Game, opts ...grpc.CallOption) (*Game, error) {
	out := new(Game)
	err := c.cc.Invoke(ctx, "/poker.Poker/SetButtonPositions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerClient) ValidatePreGame(ctx context.Context, in *Game, opts ...grpc.CallOption) (*Game, error) {
	out := new(Game)
	err := c.cc.Invoke(ctx, "/poker.Poker/ValidatePreGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerClient) NextDealer(ctx context.Context, in *Game, opts ...grpc.CallOption) (*Game, error) {
	out := new(Game)
	err := c.cc.Invoke(ctx, "/poker.Poker/NextDealer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerClient) RemovePlayerFromGame(ctx context.Context, in *Player, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/poker.Poker/RemovePlayerFromGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PokerServer is the server API for Poker service.
type PokerServer interface {
	CreatePlayer(context.Context, *Player) (*Player, error)
	CreatePlayers(context.Context, *Players) (*Players, error)
	DeletePlayers(context.Context, *Players) (*empty.Empty, error)
	GetPlayer(context.Context, *Player) (*Player, error)
	CreateGame(context.Context, *Game) (*Game, error)
	GetGame(context.Context, *Game) (*Game, error)
	DeleteGames(context.Context, *Games) (*empty.Empty, error)
	GetGamePlayersByGameId(context.Context, *Game) (*Players, error)
	GetGameByName(context.Context, *Game) (*Game, error)
	SetGamePlayers(context.Context, *Game) (*Players, error)
	GetPlayersByName(context.Context, *Players) (*Players, error)
	SetPlayerSlot(context.Context, *Player) (*Player, error)
	AllocateGameSlots(context.Context, *Game) (*Game, error)
	SetButtonPositions(context.Context, *Game) (*Game, error)
	ValidatePreGame(context.Context, *Game) (*Game, error)
	NextDealer(context.Context, *Game) (*Game, error)
	//    rpc CreateRoundFromGame(Game) returns (Round){}
	//    rpc GetRoundsFromGame(Game) returns (Round){}
	RemovePlayerFromGame(context.Context, *Player) (*empty.Empty, error)
}

// UnimplementedPokerServer can be embedded to have forward compatible implementations.
type UnimplementedPokerServer struct {
}

func (*UnimplementedPokerServer) CreatePlayer(ctx context.Context, req *Player) (*Player, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlayer not implemented")
}
func (*UnimplementedPokerServer) CreatePlayers(ctx context.Context, req *Players) (*Players, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlayers not implemented")
}
func (*UnimplementedPokerServer) DeletePlayers(ctx context.Context, req *Players) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePlayers not implemented")
}
func (*UnimplementedPokerServer) GetPlayer(ctx context.Context, req *Player) (*Player, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayer not implemented")
}
func (*UnimplementedPokerServer) CreateGame(ctx context.Context, req *Game) (*Game, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGame not implemented")
}
func (*UnimplementedPokerServer) GetGame(ctx context.Context, req *Game) (*Game, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGame not implemented")
}
func (*UnimplementedPokerServer) DeleteGames(ctx context.Context, req *Games) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGames not implemented")
}
func (*UnimplementedPokerServer) GetGamePlayersByGameId(ctx context.Context, req *Game) (*Players, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGamePlayersByGameId not implemented")
}
func (*UnimplementedPokerServer) GetGameByName(ctx context.Context, req *Game) (*Game, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGameByName not implemented")
}
func (*UnimplementedPokerServer) SetGamePlayers(ctx context.Context, req *Game) (*Players, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetGamePlayers not implemented")
}
func (*UnimplementedPokerServer) GetPlayersByName(ctx context.Context, req *Players) (*Players, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayersByName not implemented")
}
func (*UnimplementedPokerServer) SetPlayerSlot(ctx context.Context, req *Player) (*Player, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPlayerSlot not implemented")
}
func (*UnimplementedPokerServer) AllocateGameSlots(ctx context.Context, req *Game) (*Game, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllocateGameSlots not implemented")
}
func (*UnimplementedPokerServer) SetButtonPositions(ctx context.Context, req *Game) (*Game, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetButtonPositions not implemented")
}
func (*UnimplementedPokerServer) ValidatePreGame(ctx context.Context, req *Game) (*Game, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidatePreGame not implemented")
}
func (*UnimplementedPokerServer) NextDealer(ctx context.Context, req *Game) (*Game, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NextDealer not implemented")
}
func (*UnimplementedPokerServer) RemovePlayerFromGame(ctx context.Context, req *Player) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePlayerFromGame not implemented")
}

func RegisterPokerServer(s *grpc.Server, srv PokerServer) {
	s.RegisterService(&_Poker_serviceDesc, srv)
}

func _Poker_CreatePlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Player)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerServer).CreatePlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poker.Poker/CreatePlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerServer).CreatePlayer(ctx, req.(*Player))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poker_CreatePlayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Players)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerServer).CreatePlayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poker.Poker/CreatePlayers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerServer).CreatePlayers(ctx, req.(*Players))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poker_DeletePlayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Players)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerServer).DeletePlayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poker.Poker/DeletePlayers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerServer).DeletePlayers(ctx, req.(*Players))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poker_GetPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Player)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerServer).GetPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poker.Poker/GetPlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerServer).GetPlayer(ctx, req.(*Player))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poker_CreateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Game)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerServer).CreateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poker.Poker/CreateGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerServer).CreateGame(ctx, req.(*Game))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poker_GetGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Game)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerServer).GetGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poker.Poker/GetGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerServer).GetGame(ctx, req.(*Game))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poker_DeleteGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Games)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerServer).DeleteGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poker.Poker/DeleteGames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerServer).DeleteGames(ctx, req.(*Games))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poker_GetGamePlayersByGameId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Game)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerServer).GetGamePlayersByGameId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poker.Poker/GetGamePlayersByGameId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerServer).GetGamePlayersByGameId(ctx, req.(*Game))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poker_GetGameByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Game)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerServer).GetGameByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poker.Poker/GetGameByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerServer).GetGameByName(ctx, req.(*Game))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poker_SetGamePlayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Game)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerServer).SetGamePlayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poker.Poker/SetGamePlayers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerServer).SetGamePlayers(ctx, req.(*Game))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poker_GetPlayersByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Players)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerServer).GetPlayersByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poker.Poker/GetPlayersByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerServer).GetPlayersByName(ctx, req.(*Players))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poker_SetPlayerSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Player)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerServer).SetPlayerSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poker.Poker/SetPlayerSlot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerServer).SetPlayerSlot(ctx, req.(*Player))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poker_AllocateGameSlots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Game)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerServer).AllocateGameSlots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poker.Poker/AllocateGameSlots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerServer).AllocateGameSlots(ctx, req.(*Game))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poker_SetButtonPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Game)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerServer).SetButtonPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poker.Poker/SetButtonPositions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerServer).SetButtonPositions(ctx, req.(*Game))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poker_ValidatePreGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Game)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerServer).ValidatePreGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poker.Poker/ValidatePreGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerServer).ValidatePreGame(ctx, req.(*Game))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poker_NextDealer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Game)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerServer).NextDealer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poker.Poker/NextDealer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerServer).NextDealer(ctx, req.(*Game))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poker_RemovePlayerFromGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Player)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerServer).RemovePlayerFromGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poker.Poker/RemovePlayerFromGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerServer).RemovePlayerFromGame(ctx, req.(*Player))
	}
	return interceptor(ctx, in, info, handler)
}

var _Poker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "poker.Poker",
	HandlerType: (*PokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePlayer",
			Handler:    _Poker_CreatePlayer_Handler,
		},
		{
			MethodName: "CreatePlayers",
			Handler:    _Poker_CreatePlayers_Handler,
		},
		{
			MethodName: "DeletePlayers",
			Handler:    _Poker_DeletePlayers_Handler,
		},
		{
			MethodName: "GetPlayer",
			Handler:    _Poker_GetPlayer_Handler,
		},
		{
			MethodName: "CreateGame",
			Handler:    _Poker_CreateGame_Handler,
		},
		{
			MethodName: "GetGame",
			Handler:    _Poker_GetGame_Handler,
		},
		{
			MethodName: "DeleteGames",
			Handler:    _Poker_DeleteGames_Handler,
		},
		{
			MethodName: "GetGamePlayersByGameId",
			Handler:    _Poker_GetGamePlayersByGameId_Handler,
		},
		{
			MethodName: "GetGameByName",
			Handler:    _Poker_GetGameByName_Handler,
		},
		{
			MethodName: "SetGamePlayers",
			Handler:    _Poker_SetGamePlayers_Handler,
		},
		{
			MethodName: "GetPlayersByName",
			Handler:    _Poker_GetPlayersByName_Handler,
		},
		{
			MethodName: "SetPlayerSlot",
			Handler:    _Poker_SetPlayerSlot_Handler,
		},
		{
			MethodName: "AllocateGameSlots",
			Handler:    _Poker_AllocateGameSlots_Handler,
		},
		{
			MethodName: "SetButtonPositions",
			Handler:    _Poker_SetButtonPositions_Handler,
		},
		{
			MethodName: "ValidatePreGame",
			Handler:    _Poker_ValidatePreGame_Handler,
		},
		{
			MethodName: "NextDealer",
			Handler:    _Poker_NextDealer_Handler,
		},
		{
			MethodName: "RemovePlayerFromGame",
			Handler:    _Poker_RemovePlayerFromGame_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobufs/poker.proto",
}
